spring:
  data:
    mongodb:
      uri: ${mongodb_uri}
      database: ${database_name}
      auto-index-creation: true
  active:
    profile:
  main:
    allow-circular-references: true
  redis:
    host: ${host_name}
    port:
    password: ${host_password}
  mail:
    host: notmention@gmail.com
    port: yyy
    username: notmention@gmail.com
    password: xxxx yyyy xxxx yyyy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: xxyy
  servlet:
    context-path: ${/path}

weather:
  api:
    key: ${weather_api_key}



