spring:
  data:
    mongodb:
      uri: x
      database: y
      auto-index-creation: true
  active:
    profile:
  main:
    allow-circular-references: true
  redis:
    host: x
    port:
    password: x
  mail:
    host: notmention@gmail.com
    port: yyy
    username: notmention@gmail.com
    password: xxxx yyyy xxxx yyyy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: xxyy
  servlet:
    context-path: /path

weather:
  api:
    key: ${weather_api}



